# Generated by Django 5.2.11 on 2026-02-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('maintenance_due_days', 'Maintenance due within (days)'), ('maintenance_overdue', 'Maintenance overdue alert')], max_length=64, unique=True)),
                ('value_int', models.IntegerField(blank=True, default=7, help_text='Numeric value (e.g. days)', null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['name'],
            },
        ),
    ]
