# Generated by Django 5.2.11 on 2026-03-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('engine_temperature_c', 'Engine temperature (°C)'), ('fuel_level_pct', 'Fuel level (%)'), ('speed_kmh', 'Speed (km/h)'), ('rpm', 'Engine RPM'), ('mileage', 'Mileage (km)'), ('voltage', 'Battery voltage (V)'), ('throttle_pct', 'Throttle position (%)')], max_length=64)),
                ('operator', models.CharField(choices=[('gte', '≥ (greater or equal)'), ('lte', '≤ (less or equal)'), ('gt', '> (greater)'), ('lt', '< (less)')], max_length=8)),
                ('value_float', models.FloatField(help_text='Threshold value')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('description', models.CharField(blank=True, help_text='Optional label for this rule (e.g. "Engine overheating warning")', max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Threshold',
                'verbose_name_plural': 'Alert Thresholds',
                'ordering': ['attribute', 'value_float'],
            },
        ),
    ]
