# Generated by Django 5.2.11 on 2026-03-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_alert_threshold_and_threshold_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='name',
            field=models.CharField(choices=[('maintenance_due_days', 'Maintenance due within (days)'), ('maintenance_overdue', 'Maintenance overdue alert'), ('compliance_expiring_days', 'Compliance expiring within (days)'), ('workorder_due_days', 'Work orders due within (days)')], max_length=64, unique=True),
        ),
    ]
