# Generated by Django 5.2.11 on 2026-04-06 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0009_fr18_fr19_sensors_gps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('optimization_priority', models.CharField(choices=[('distance', 'Shortest distance'), ('time', 'Fastest time'), ('fuel', 'Lowest fuel cost')], default='distance', max_length=10)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('selected', 'Selected'), ('completed', 'Completed')], default='planning', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_number', models.PositiveSmallIntegerField(default=1)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_time_min', models.PositiveIntegerField()),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vehicle_condition_impact', models.TextField(blank=True)),
                ('recommended', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='routes.route')),
            ],
            options={
                'ordering': ['alternative_number'],
            },
        ),
    ]
