# Generated by Django 5.2.11 on 2026-02-10 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('maintenance_interval_days', models.PositiveIntegerField(default=90, help_text='Default maintenance interval in days')),
                ('maintenance_interval_km', models.PositiveIntegerField(default=10000, help_text='Default maintenance interval in kilometers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(help_text='Vehicle Identification Number', max_length=17, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='active', max_length=20)),
                ('current_mileage', models.PositiveIntegerField(default=0, help_text='Current mileage in kilometers')),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('fuel_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel capacity in liters', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_telemetry_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicles', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehicletype')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h', max_digits=6, null=True)),
                ('fuel_level_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel level percentage 0-100', max_digits=5, null=True)),
                ('engine_temperature_c', models.DecimalField(blank=True, decimal_places=2, help_text='Engine temperature in Celsius', max_digits=5, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rpm', models.PositiveIntegerField(blank=True, help_text='Engine RPM', null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='Odometer reading in km', null=True)),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, help_text='Battery voltage', max_digits=5, null=True)),
                ('throttle_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Throttle position percentage', max_digits=5, null=True)),
                ('brake_status', models.BooleanField(blank=True, help_text='Brake pedal pressed', null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_readings', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Telemetry',
                'verbose_name_plural': 'Vehicle Telemetry',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', 'timestamp'], name='veh_telem_vehicle_ts_idx')],
            },
        ),
    ]
