# Generated by Django 5.2.11 on 2026-02-10 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_telemetry_and_last_telemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_engine_temp', 'High engine temperature'), ('anomalous_fuel', 'Anomalous fuel consumption'), ('harsh_driving', 'Harsh driving'), ('prolonged_idle', 'Prolonged idling'), ('maintenance_mileage', 'Maintenance due by mileage'), ('maintenance_time', 'Maintenance due by time'), ('statistical_anomaly', 'Statistical anomaly')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('message', models.TextField()),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, help_text='0-1 confidence score', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Alert',
                'verbose_name_plural': 'Vehicle Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle', 'created_at'], name='veh_alert_vehicle_ts_idx')],
            },
        ),
    ]
