# Generated by Django 5.2.11 on 2026-02-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_engine_temp', 'High engine temperature'), ('anomalous_fuel', 'Anomalous fuel consumption'), ('harsh_driving', 'Harsh driving'), ('prolonged_idle', 'Prolonged idling'), ('maintenance_mileage', 'Maintenance due by mileage'), ('maintenance_time', 'Maintenance due by time'), ('statistical_anomaly', 'Statistical anomaly')], help_text='Alert type this playbook applies to', max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('steps', models.JSONField(default=list, help_text='List of step strings (e.g. ["Check coolant", "Schedule inspection"])')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Playbook',
                'verbose_name_plural': 'Playbooks',
                'ordering': ['alert_type'],
            },
        ),
        migrations.CreateModel(
            name='Runbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alert_type', models.CharField(blank=True, choices=[('high_engine_temp', 'High engine temperature'), ('anomalous_fuel', 'Anomalous fuel consumption'), ('harsh_driving', 'Harsh driving'), ('prolonged_idle', 'Prolonged idling'), ('maintenance_mileage', 'Maintenance due by mileage'), ('maintenance_time', 'Maintenance due by time'), ('statistical_anomaly', 'Statistical anomaly')], help_text='Optional: only for this alert type', max_length=32, null=True)),
                ('action_type', models.CharField(choices=[('mark_alert_read', 'Mark alert as read'), ('create_maintenance_task', 'Create maintenance task'), ('dismiss_alert', 'Dismiss alert')], max_length=32)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Runbook',
                'verbose_name_plural': 'Runbooks',
                'ordering': ['name'],
            },
        ),
    ]
