# Generated by Django 5.2.11 on 2026-02-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_playbook_runbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclealert',
            name='timeframe_text',
            field=models.CharField(blank=True, help_text='e.g. "Próximos 7 días", "En 500 km" (FR9)', max_length=128),
        ),
    ]
