# Generated by Django 5.2.11 on 2026-02-12 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alert_timeframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('inspection', 'Inspection'), ('certification', 'Certification'), ('license', 'License'), ('registration', 'Registration'), ('insurance', 'Insurance'), ('other', 'Other')], default='inspection', max_length=20)),
                ('name', models.CharField(help_text='Short name (e.g. Annual inspection)', max_length=200)),
                ('expiration_date', models.DateField()),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('document_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_requirements', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Compliance Requirement',
                'verbose_name_plural': 'Compliance Requirements',
                'ordering': ['expiration_date'],
            },
        ),
    ]
