# Generated by Django 5.2.11 on 2026-02-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_compliance_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclealert',
            name='suggestion_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], db_index=True, max_length=16, null=True),
        ),
    ]
