# Generated by Django 5.2.11 on 2026-03-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alert_suggestion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='alert_type',
            field=models.CharField(choices=[('high_engine_temp', 'High engine temperature'), ('anomalous_fuel', 'Anomalous fuel consumption'), ('harsh_driving', 'Harsh driving'), ('prolonged_idle', 'Prolonged idling'), ('maintenance_mileage', 'Maintenance due by mileage'), ('maintenance_time', 'Maintenance due by time'), ('statistical_anomaly', 'Statistical anomaly'), ('threshold_exceeded', 'Custom threshold exceeded')], help_text='Alert type this playbook applies to', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='runbook',
            name='alert_type',
            field=models.CharField(blank=True, choices=[('high_engine_temp', 'High engine temperature'), ('anomalous_fuel', 'Anomalous fuel consumption'), ('harsh_driving', 'Harsh driving'), ('prolonged_idle', 'Prolonged idling'), ('maintenance_mileage', 'Maintenance due by mileage'), ('maintenance_time', 'Maintenance due by time'), ('statistical_anomaly', 'Statistical anomaly'), ('threshold_exceeded', 'Custom threshold exceeded')], help_text='Optional: only for this alert type', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclealert',
            name='alert_type',
            field=models.CharField(choices=[('high_engine_temp', 'High engine temperature'), ('anomalous_fuel', 'Anomalous fuel consumption'), ('harsh_driving', 'Harsh driving'), ('prolonged_idle', 'Prolonged idling'), ('maintenance_mileage', 'Maintenance due by mileage'), ('maintenance_time', 'Maintenance due by time'), ('statistical_anomaly', 'Statistical anomaly'), ('threshold_exceeded', 'Custom threshold exceeded')], max_length=32),
        ),
    ]
