# Generated by Django 5.2.11 on 2026-04-06 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_add_alert_threshold_and_threshold_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('idle_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('avg_speed_kmh', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_speed_kmh', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('aggressive_events', models.PositiveIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_patterns', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='GPSReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_readings', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', 'timestamp'], name='gps_veh_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature (°C)'), ('vibration', 'Vibration (mm/s)'), ('pressure', 'Pressure (PSI)'), ('oil_level', 'Oil Level (%)'), ('battery_voltage', 'Battery Voltage (V)'), ('tire_pressure', 'Tire Pressure (PSI)')], max_length=20)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('api', 'API'), ('csv', 'CSV Upload'), ('manual', 'Manual Entry')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', 'sensor_type', 'timestamp'], name='sensor_veh_type_ts_idx')],
            },
        ),
    ]
