# Generated by Django 5.2.11 on 2026-04-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_fr18_fr19_sensors_gps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Temperature (C)'), ('vibration', 'Vibration (mm/s)'), ('pressure', 'Pressure (PSI)'), ('oil_level', 'Oil Level (%)'), ('battery_voltage', 'Battery Voltage (V)'), ('tire_pressure', 'Tire Pressure (PSI)')], max_length=20),
        ),
    ]
