# Generated by Django 5.2.11 on 2026-04-30 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_alter_sensorreading_sensor_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclealert',
            name='criticality_reason',
            field=models.TextField(blank=True, help_text='Human-readable reason for the assigned criticality.'),
        ),
        migrations.AddField(
            model_name='vehiclealert',
            name='severity_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclealert',
            name='severity_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severity_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclealert',
            name='severity_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiclealert',
            name='suggestion_dismiss_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiclealert',
            name='suggestion_handled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclealert',
            name='suggestion_priority',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='vehiclealert',
            name='suggestion_scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
