# Generated by Django 5.2.11 on 2026-05-13 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vehicles', '0011_vehiclealert_criticality_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='users.organization'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(help_text='Vehicle Identification Number', max_length=17),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('organization', 'license_plate'), name='vehicles_vehicle_org_plate_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('organization', 'vin'), name='vehicles_vehicle_org_vin_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vehicletype',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='vehicles_vehicletype_org_name_uniq'),
        ),
    ]
