# Generated by Django 5.2.11 on 2026-04-30 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('vehicles', 'Vehicles'), ('maintenance', 'Maintenance'), ('predictions', 'Predictions'), ('inventory', 'Inventory'), ('suppliers', 'Suppliers'), ('audit', 'Audit Log'), ('sensors', 'Sensor Readings'), ('gps', 'GPS Readings')], max_length=32)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel-compatible CSV')], default='csv', max_length=8)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('queued', 'Queued'), ('failed', 'Failed')], default='completed', max_length=16)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('report_type', models.CharField(max_length=64)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=16)),
                ('recipients', models.TextField(blank=True, help_text='Comma-separated email list')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
